# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'TESTVIEW',
                'managed': False,
            },
        ),
    ]
