# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaeum', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='owner',
        ),
    ]
